### ISSUE TITLE
Mac M1 controls

### ISSUE THREAD

**Issue by Rucadi** [LonelyRun/Shinsi2#10]
Hi,
your app works flawlessly with the new MAC M1,  which maybe it's worth mentioning in the README. 
(Installed using appdb.to)

However, I think it can be improved easily if keyboard support is added. 
Right now, it works using the MAC Touch Alternatives, which translates the keyboard into touch actions.

Thank you for your awesome app!

**Comment by LonelyRun** [comment]
I'm sorry, but I don't have any mac M1 available here
