### ISSUE TITLE
May I install it without XCode?

### ISSUE THREAD

**Issue by sundevista** [LonelyRun/Shinsi2#18]
I have no jailbreak on my phone. I have no XCode or any MacOS device too. So, May I install it without this?

**Comment by OYcedar** [comment]
you can install it with [AltStore](https://altstore.io/) on windows ,and you need have a apple ID. download ipa in release,and install by altstore.

**Comment by sundevista** [comment]
I`ll try it, thanks

**Comment by sundevista** [comment]
It works
