### ISSUE TITLE
無法正常顯示封面和內頁的縮圖，只能看到色塊(詳細如圖)

### ISSUE THREAD

**Issue by glad999** [LonelyRun/Shinsi2#20]
可正常觀看表站和裏站內容，但都無法順利載入縮圖，如圖:
![如圖片](https://i.imgur.com/AZTcvD1.jpg)

**Comment by OYcedar** [comment]
you can try uninstall and reinstall. it's look like DownsamplingImgae error.

**Comment by Temaz-epam** [comment]
This is still an issue, even uninstalling and reinstalling. The last version that works is 1.6.0. This problem still occurs on 1.9.3.
