### ISSUE TITLE
如何獲得Ex key

### ISSUE THREAD

**Issue by yommu947** [LonelyRun/Shinsi2#21]
請問如何獲得ex key進入ex hentai

**Comment by LonelyRun** [comment]
exkey就是您在里站的 cookie 序列，需要在网页端进入里站，在控制台的 cookie 列表获取 ipb_pass_hash, ipb_member_id, igneous 变量对应的值
按照 [ipb_pass_hash][ipb_member_id]x[igneous] 顺序组合后即为 exkey

**Comment by yommu947** [comment]
> exkey就是您在里站的 cookie 序列，需要在网页端进入里站，在控制台的 cookie 列表获取 ipb_pass_hash, ipb_member_id, igneous 变量对应的值
> 按照 [ipb_pass_hash][ipb_member_id]x[igneous] 顺序组合后即为 exkey

我成功使用ex key登入，但還是不能使用ex頁面

**Comment by LonelyRun** [comment]
是ex列表页面显示为空么？ 因为看不到实际的情况
我这边只能做以下猜测
1.网络问题
2.exkey问题（app exkey登录模块仅对exkey格式做了校验， 无法判断其有效性）
