### ISSUE TITLE
關於顯示封面和內頁的縮圖的問題補充

### ISSUE THREAD

**Issue by glad999** [LonelyRun/Shinsi2#22]
補充 [#20](https://github.com/LonelyRun/Shinsi2/issues/20)
==
發現只要在1.6.0的時候顯示正常，不會有問題
測試環境:
iPhone 6
ios 12.5.2

**Comment by CaiMiao** [comment]
同样问题。
iPad mini5
iOS 13.5

**Comment by hentaisama** [comment]
希望作者能解决这个问题，这个软件还是挺好用的

**Comment by CaiMiao** [comment]
@LonelyRun Won't fix? can provide screenshot/log.

**Comment by LonelyRun** [comment]
你是通过ipa安装还是自己编译的？ ipa的话我这边还没发布新的release

**Comment by LonelyRun** [comment]
@CaiMiao 你是通过ipa安装还是自己编译的？ ipa的话我这边还没发布新的release

**Comment by CaiMiao** [comment]
> @CaiMiao 你是通过ipa安装还是自己编译的？ ipa的话我这边还没发布新的release

通过ipa的。  
看到commit了，谢谢。希望快些发布新版。

**Comment by CaiMiao** [comment]
@LonelyRun 
下载的图库依然是色块。希望跟进一下
![5AC3782D-8B77-42FB-BE10-56D52C6855F1](https://user-images.githubusercontent.com/4640483/119297811-49889d80-bc8e-11eb-87e1-6fbaa08f7cea.jpeg)
